version: "3"
services:
    php:
        build: php/
        ports: 
            - "30000:80"
        volumes:
            - ./php/www:/var/www/html/
        links:
            - db
    db:
        image: mariadb
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - ./sql/:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 50000:8080
        links: 
            - db:db
volumes:
    persistent: